# Generates the dbghelp.dll proxy's exports from System32\dbghelp.dll:
#   loader/proxy/Exports.asm        one jump stub per export: jmp [g_dbghelpReal + i*8]
#   loader/proxy/Exports.def        Name=dk2s_<i> @ordinal (same names and ordinals as the real dll)
#   loader/proxy/ExportNames.inc    the export names, used at startup to fill g_dbghelpReal from the real dll
# Stub labels are numbered because some dbghelp export names (sym, block, dh...) aren't safe assembler labels.
param(
    [string]$Source = "$env:SystemRoot\System32\dbghelp.dll",
    [string]$OutDir = "$PSScriptRoot\..\loader\proxy"
)

$bytes = [IO.File]::ReadAllBytes($Source)
function U16($o) { [BitConverter]::ToUInt16($bytes, $o) }
function U32($o) { [BitConverter]::ToUInt32($bytes, $o) }

$pe = U32 0x3C
$numSections = U16 ($pe + 6)
$optSize = U16 ($pe + 20)
$opt = $pe + 24
if ((U16 $opt) -ne 0x20B) { throw "$Source is not a PE32+ (x64) image" }
$exportRva = U32 ($opt + 112)

$sections = for ($i = 0; $i -lt $numSections; $i++) {
    $s = $opt + $optSize + $i * 40
    [pscustomobject]@{ Va = (U32 ($s + 12)); Size = [Math]::Max((U32 ($s + 8)), (U32 ($s + 16))); Raw = (U32 ($s + 20)) }
}
function RvaToOffset($rva) {
    foreach ($s in $sections) { if ($rva -ge $s.Va -and $rva -lt $s.Va + $s.Size) { return $rva - $s.Va + $s.Raw } }
    throw "RVA 0x{0:X} not in any section" -f $rva
}
function CString($off) {
    $end = $off; while ($bytes[$end] -ne 0) { $end++ }
    [Text.Encoding]::ASCII.GetString($bytes, $off, $end - $off)
}

$exp = RvaToOffset $exportRva
$ordinalBase = U32 ($exp + 16)
$numNames = U32 ($exp + 24)
$namesOff = RvaToOffset (U32 ($exp + 32))
$ordsOff = RvaToOffset (U32 ($exp + 36))

$header = 'Generated by tools/gen_exports.ps1 from System32\dbghelp.dll - do not edit'
$asm = @("; $header", 'EXTERN g_dbghelpReal:QWORD', '.code')
$def = @("; $header", 'LIBRARY dbghelp', 'EXPORTS')
$names = @("// $header")
for ($i = 0; $i -lt $numNames; $i++) {
    $name = CString (RvaToOffset (U32 ($namesOff + 4 * $i)))
    $ordinal = (U16 ($ordsOff + 2 * $i)) + $ordinalBase
    $asm += "dk2s_$i PROC", "    jmp qword ptr [g_dbghelpReal + $($i * 8)]", "dk2s_$i ENDP"
    $def += "    $name=dk2s_$i @$ordinal"
    $names += "`"$name`","
}
$asm += 'END'

Set-Content -Path (Join-Path $OutDir 'Exports.asm') -Value $asm -Encoding ascii
Set-Content -Path (Join-Path $OutDir 'Exports.def') -Value $def -Encoding ascii
Set-Content -Path (Join-Path $OutDir 'ExportNames.inc') -Value $names -Encoding ascii
Write-Host "Wrote $numNames export stubs to $OutDir"
